name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: check clang-format
        run: git ls-files *.{cpp,h} | xargs clang-format -i && git diff --exit-code

      - name: build app
        run: make

      - name: build test
        run: make test
        
      - name: run test
        run: ./bin/test